builds:
  - binary: ahchcli
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: ahchcli
    homepage: "https://github.com/amrhsyn/ahchcli/"
    tap:
      owner: amrhsyn
      name: homebrew-amrhsyn
    commit_author:
      name: amrhsyn
      email: ahch.pv@gmail.com

checksum:
  name_template: 'checksums.txt'
